apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crowd-filler
  namespace: cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: simple
              image: cr.yandex/crp4g65pbp8qf4mtcos7/simple
              env:
                - name: RUN_ONCE
                  value: "true"
          restartPolicy: Never


