apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  selector:
    name: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: simple-app
  template:
    metadata:
      labels:
        name: simple-app
        app: simple
    spec:
      containers:
        - name: simple-app
          image: cr.yandex/crp4g65pbp8qf4mtcos7/simple:v14
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
