name: Deploy to aurora

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.REGISTRY }}/simple:${{ github.sha }}
          
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set context
      uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: https://84.252.142.144
        k8s-secret: ${{ secrets.K8S_SECRET }}
      id: setcontext

    - uses: Azure/k8s-deploy@v1.4
      with:
        manifests: kube/simple-app.yaml
        images: '${{ secrets.REGISTRY }}/simple:${{ github.sha }}'
